#!/bin/sh

build() { 
        add_binary bcachefs
	add_binary rsync
	add_binary bash
	add_module overlay
	add_module loop
	add_module vfat
	add_runscript
}

help() {
	cat << HELPEOF
Rollback bcachefs
HELPEOF
}
