#!/bin/sh

build() { 
	add_binary bcachefs
	add_binary bash
	add_module overlay
	add_module loop
	add_binary rsync
	add_binary unsquashfs
	add_binary mksquashfs
	add_runscript
}

help() {
	cat << HELPEOF
Rollback bcachefs and boot into snapshots
HELPEOF
}
